using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;

using dnlib.DotNet;
using dnlib.DotNet.MD;
using dnlib.DotNet.Emit;

using VProtect.Core.VM;
using VProtect.Core.Utilites;

using DOpCodes = dnlib.DotNet.Emit.OpCodes;

namespace VProtect.Core.Runtime
{
    internal class RTConstants
    {
        static readonly Dictionary<Code, string> ConstantsMap = new Dictionary<Code, string>
        {
                { Code.Add, "Add" },
                { Code.Add_Ovf, "Add_Ovf" },
                { Code.Add_Ovf_Un, "Add_Ovf_Un" },
                { Code.And, "And" },
                { Code.Arglist, "Arglist" },
                { Code.Beq, "Beq" },
                { Code.Beq_S, "Beq_S" },
                { Code.Bge, "Bge" },
                { Code.Bge_S, "Bge_S" },
                { Code.Bge_Un, "Bge_Un" },
                { Code.Bge_Un_S, "Bge_Un_S" },
                { Code.Bgt, "Bgt" },
                { Code.Bgt_S, "Bgt_S" },
                { Code.Bgt_Un, "Bgt_Un" },
                { Code.Bgt_Un_S, "Bgt_Un_S" },
                { Code.Ble, "Ble" },
                { Code.Ble_S, "Ble_S" },
                { Code.Ble_Un, "Ble_Un" },
                { Code.Ble_Un_S, "Ble_Un_S" },
                { Code.Blt, "Blt" },
                { Code.Blt_S, "Blt_S" },
                { Code.Blt_Un, "Blt_Un" },
                { Code.Blt_Un_S, "Blt_Un_S" },
                { Code.Bne_Un, "Bne_Un" },
                { Code.Bne_Un_S, "Bne_Un_S" },
                { Code.Box, "Box" },
                { Code.Br, "Br" },
                { Code.Br_S, "Br_S" },
                { Code.Break, "Break" },
                { Code.Brfalse, "Brfalse" },
                { Code.Brfalse_S, "Brfalse_S" },
                { Code.Brtrue, "Brtrue" },
                { Code.Brtrue_S, "Brtrue_S" },
                { Code.Call, "Call" },
                { Code.Calli, "Calli" },
                { Code.Callvirt, "Callvirt" },
                { Code.Castclass, "Castclass" },
                { Code.Ceq, "Ceq" },
                { Code.Cgt, "Cgt" },
                { Code.Cgt_Un, "Cgt_Un" },
                { Code.Ckfinite, "Ckfinite" },
                { Code.Clt, "Clt" },
                { Code.Clt_Un, "Clt_Un" },
                { Code.Constrained, "Constrained" },
                { Code.Conv_I, "Conv_I" },
                { Code.Conv_I1, "Conv_I1" },
                { Code.Conv_I2, "Conv_I2" },
                { Code.Conv_I4, "Conv_I4" },
                { Code.Conv_I8, "Conv_I8" },
                { Code.Conv_Ovf_I, "Conv_Ovf_I" },
                { Code.Conv_Ovf_I_Un, "Conv_Ovf_I_Un" },
                { Code.Conv_Ovf_I1, "Conv_Ovf_I1" },
                { Code.Conv_Ovf_I1_Un, "Conv_Ovf_I1_Un" },
                { Code.Conv_Ovf_I2, "Conv_Ovf_I2" },
                { Code.Conv_Ovf_I2_Un, "Conv_Ovf_I2_Un" },
                { Code.Conv_Ovf_I4, "Conv_Ovf_I4" },
                { Code.Conv_Ovf_I4_Un, "Conv_Ovf_I4_Un" },
                { Code.Conv_Ovf_I8, "Conv_Ovf_I8" },
                { Code.Conv_Ovf_I8_Un, "Conv_Ovf_I8_Un" },
                { Code.Conv_Ovf_U, "Conv_Ovf_U" },
                { Code.Conv_Ovf_U_Un, "Conv_Ovf_U_Un" },
                { Code.Conv_Ovf_U1, "Conv_Ovf_U1" },
                { Code.Conv_Ovf_U1_Un, "Conv_Ovf_U1_Un" },
                { Code.Conv_Ovf_U2, "Conv_Ovf_U2" },
                { Code.Conv_Ovf_U2_Un, "Conv_Ovf_U2_Un" },
                { Code.Conv_Ovf_U4, "Conv_Ovf_U4" },
                { Code.Conv_Ovf_U4_Un, "Conv_Ovf_U4_Un" },
                { Code.Conv_Ovf_U8, "Conv_Ovf_U8" },
                { Code.Conv_Ovf_U8_Un, "Conv_Ovf_U8_Un" },
                { Code.Conv_R_Un, "Conv_R_Un" },
                { Code.Conv_R4, "Conv_R4" },
                { Code.Conv_R8, "Conv_R8" },
                { Code.Conv_U, "Conv_U" },
                { Code.Conv_U1, "Conv_U1" },
                { Code.Conv_U2, "Conv_U2" },
                { Code.Conv_U4, "Conv_U4" },
                { Code.Conv_U8, "Conv_U8" },
                { Code.Cpblk, "Cpblk" },
                { Code.Cpobj, "Cpobj" },
                { Code.Div, "Div" },
                { Code.Div_Un, "Div_Un" },
                { Code.Dup, "Dup" },
                { Code.Endfilter, "Endfilter" },
                { Code.Endfinally, "Endfinally" },
                { Code.Initblk, "Initblk" },
                { Code.Initobj, "Initobj" },
                { Code.Isinst, "Isinst" },
                { Code.Jmp, "Jmp" },
                { Code.Ldarg, "Ldarg" },
                { Code.Ldarg_0, "Ldarg_0" },
                { Code.Ldarg_1, "Ldarg_1" },
                { Code.Ldarg_2, "Ldarg_2" },
                { Code.Ldarg_3, "Ldarg_3" },
                { Code.Ldarg_S, "Ldarg_S" },
                { Code.Ldarga, "Ldarga" },
                { Code.Ldarga_S, "Ldarga_S" },
                { Code.Ldc_I4, "Ldc_I4" },
                { Code.Ldc_I4_0, "Ldc_I4_0" },
                { Code.Ldc_I4_1, "Ldc_I4_1" },
                { Code.Ldc_I4_2, "Ldc_I4_2" },
                { Code.Ldc_I4_3, "Ldc_I4_3" },
                { Code.Ldc_I4_4, "Ldc_I4_4" },
                { Code.Ldc_I4_5, "Ldc_I4_5" },
                { Code.Ldc_I4_6, "Ldc_I4_6" },
                { Code.Ldc_I4_7, "Ldc_I4_7" },
                { Code.Ldc_I4_8, "Ldc_I4_8" },
                { Code.Ldc_I4_M1, "Ldc_I4_M1" },
                { Code.Ldc_I4_S, "Ldc_I4_S" },
                { Code.Ldc_I8, "Ldc_I8" },
                { Code.Ldc_R4, "Ldc_R4" },
                { Code.Ldc_R8, "Ldc_R8" },
                { Code.Ldelem, "Ldelem" },
                { Code.Ldelem_I, "Ldelem_I" },
                { Code.Ldelem_I1, "Ldelem_I1" },
                { Code.Ldelem_I2, "Ldelem_I2" },
                { Code.Ldelem_I4, "Ldelem_I4" },
                { Code.Ldelem_I8, "Ldelem_I8" },
                { Code.Ldelem_R4, "Ldelem_R4" },
                { Code.Ldelem_R8, "Ldelem_R8" },
                { Code.Ldelem_Ref, "Ldelem_Ref" },
                { Code.Ldelem_U1, "Ldelem_U1" },
                { Code.Ldelem_U2, "Ldelem_U2" },
                { Code.Ldelem_U4, "Ldelem_U4" },
                { Code.Ldelema, "Ldelema" },
                { Code.Ldfld, "Ldfld" },
                { Code.Ldflda, "Ldflda" },
                { Code.Ldftn, "Ldftn" },
                { Code.Ldind_I, "Ldind_I" },
                { Code.Ldind_I1, "Ldind_I1" },
                { Code.Ldind_I2, "Ldind_I2" },
                { Code.Ldind_I4, "Ldind_I4" },
                { Code.Ldind_I8, "Ldind_I8" },
                { Code.Ldind_R4, "Ldind_R4" },
                { Code.Ldind_R8, "Ldind_R8" },
                { Code.Ldind_Ref, "Ldind_Ref" },
                { Code.Ldind_U1, "Ldind_U1" },
                { Code.Ldind_U2, "Ldind_U2" },
                { Code.Ldind_U4, "Ldind_U4" },
                { Code.Ldlen, "Ldlen" },
                { Code.Ldloc, "Ldloc" },
                { Code.Ldloc_0, "Ldloc_0" },
                { Code.Ldloc_1, "Ldloc_1" },
                { Code.Ldloc_2, "Ldloc_2" },
                { Code.Ldloc_3, "Ldloc_3" },
                { Code.Ldloc_S, "Ldloc_S" },
                { Code.Ldloca, "Ldloca" },
                { Code.Ldloca_S, "Ldloca_S" },
                { Code.Ldnull, "Ldnull" },
                { Code.Ldobj, "Ldobj" },
                { Code.Ldsfld, "Ldsfld" },
                { Code.Ldsflda, "Ldsflda" },
                { Code.Ldstr, "Ldstr" },
                { Code.Ldtoken, "Ldtoken" },
                { Code.Ldvirtftn, "Ldvirtftn" },
                { Code.Leave, "Leave" },
                { Code.Leave_S, "Leave_S" },
                { Code.Localloc, "Localloc" },
                { Code.Mkrefany, "Mkrefany" },
                { Code.Mul, "Mul" },
                { Code.Mul_Ovf, "Mul_Ovf" },
                { Code.Mul_Ovf_Un, "Mul_Ovf_Un" },
                { Code.Neg, "Neg" },
                { Code.Newarr, "Newarr" },
                { Code.Newobj, "Newobj" },
                { Code.Nop, "Nop" },
                { Code.Not, "Not" },
                { Code.Or, "Or" },
                { Code.Pop, "Pop" },
                { Code.Prefix1, "Prefix1" },
                { Code.Prefix2, "Prefix2" },
                { Code.Prefix3, "Prefix3" },
                { Code.Prefix4, "Prefix4" },
                { Code.Prefix5, "Prefix5" },
                { Code.Prefix6, "Prefix6" },
                { Code.Prefix7, "Prefix7" },
                { Code.Prefixref, "Prefixref" },
                { Code.Readonly, "Readonly" },
                { Code.Refanytype, "Refanytype" },
                { Code.Refanyval, "Refanyval" },
                { Code.Rem, "Rem" },
                { Code.Rem_Un, "Rem_Un" },
                { Code.Ret, "Ret" },
                { Code.Rethrow, "Rethrow" },
                { Code.Shl, "Shl" },
                { Code.Shr, "Shr" },
                { Code.Shr_Un, "Shr_Un" },
                { Code.Sizeof, "Sizeof" },
                { Code.Starg, "Starg" },
                { Code.Starg_S, "Starg_S" },
                { Code.Stelem, "Stelem" },
                { Code.Stelem_I, "Stelem_I" },
                { Code.Stelem_I1, "Stelem_I1" },
                { Code.Stelem_I2, "Stelem_I2" },
                { Code.Stelem_I4, "Stelem_I4" },
                { Code.Stelem_I8, "Stelem_I8" },
                { Code.Stelem_R4, "Stelem_R4" },
                { Code.Stelem_R8, "Stelem_R8" },
                { Code.Stelem_Ref, "Stelem_Ref" },
                { Code.Stfld, "Stfld" },
                { Code.Stind_I, "Stind_I" },
                { Code.Stind_I1, "Stind_I1" },
                { Code.Stind_I2, "Stind_I2" },
                { Code.Stind_I4, "Stind_I4" },
                { Code.Stind_I8, "Stind_I8" },
                { Code.Stind_R4, "Stind_R4" },
                { Code.Stind_R8, "Stind_R8" },
                { Code.Stind_Ref, "Stind_Ref" },
                { Code.Stloc, "Stloc" },
                { Code.Stloc_0, "Stloc_0" },
                { Code.Stloc_1, "Stloc_1" },
                { Code.Stloc_2, "Stloc_2" },
                { Code.Stloc_3, "Stloc_3" },
                { Code.Stloc_S, "Stloc_S" },
                { Code.Stobj, "Stobj" },
                { Code.Stsfld, "Stsfld" },
                { Code.Sub, "Sub" },
                { Code.Sub_Ovf, "Sub_Ovf" },
                { Code.Sub_Ovf_Un, "Sub_Ovf_Un" },
                { Code.Switch, "Switch" },
                { Code.Tailcall, "Tailcall" },
                { Code.Throw, "Throw" },
                { Code.Unaligned, "Unaligned" },
                { Code.Unbox, "Unbox" },
                { Code.Unbox_Any, "Unbox_Any" },
                { Code.Volatile, "Volatile" },
                { Code.Xor, "Xor" }
        };
        static readonly Dictionary<Code, KeyValuePair<int, int>> OpCodesMap = new Dictionary<Code, KeyValuePair<int, int>>
        {
            { Code.Nop,            new KeyValuePair<int, int>(6556325, 0) },
            { Code.Break,          new KeyValuePair<int, int>(6556197, 1) },
            { Code.Ldarg_0,        new KeyValuePair<int, int>(275120805, 2) },
            { Code.Ldarg_1,        new KeyValuePair<int, int>(275120805, 3) },
            { Code.Ldarg_2,        new KeyValuePair<int, int>(275120805, 4) },
            { Code.Ldarg_3,        new KeyValuePair<int, int>(275120805, 5) },
            { Code.Ldloc_0,        new KeyValuePair<int, int>(275120805, 6) },
            { Code.Ldloc_1,        new KeyValuePair<int, int>(275120805, 7) },
            { Code.Ldloc_2,        new KeyValuePair<int, int>(275120805, 8) },
            { Code.Ldloc_3,        new KeyValuePair<int, int>(275120805, 9) },
            { Code.Stloc_0,        new KeyValuePair<int, int>(-261877083, 10) },
            { Code.Stloc_1,        new KeyValuePair<int, int>(-261877083, 11) },
            { Code.Stloc_2,        new KeyValuePair<int, int>(-261877083, 12) },
            { Code.Stloc_3,        new KeyValuePair<int, int>(-261877083, 13) },
            { Code.Ldarg_S,        new KeyValuePair<int, int>(275120818, 14) },
            { Code.Ldarga_S,       new KeyValuePair<int, int>(275382962, 15) },
            { Code.Starg_S,        new KeyValuePair<int, int>(-261877070, 16) },
            { Code.Ldloc_S,        new KeyValuePair<int, int>(275120818, 17) },
            { Code.Ldloca_S,       new KeyValuePair<int, int>(275382962, 18) },
            { Code.Stloc_S,        new KeyValuePair<int, int>(-261877070, 19) },
            { Code.Ldnull,         new KeyValuePair<int, int>(275909285, 20) },
            { Code.Ldc_I4_M1,      new KeyValuePair<int, int>(275382949, 21) },
            { Code.Ldc_I4_0,       new KeyValuePair<int, int>(275382949, 22) },
            { Code.Ldc_I4_1,       new KeyValuePair<int, int>(275382949, 23) },
            { Code.Ldc_I4_2,       new KeyValuePair<int, int>(275382949, 24) },
            { Code.Ldc_I4_3,       new KeyValuePair<int, int>(275382949, 25) },
            { Code.Ldc_I4_4,       new KeyValuePair<int, int>(275382949, 26) },
            { Code.Ldc_I4_5,       new KeyValuePair<int, int>(275382949, 27) },
            { Code.Ldc_I4_6,       new KeyValuePair<int, int>(275382949, 28) },
            { Code.Ldc_I4_7,       new KeyValuePair<int, int>(275382949, 29) },
            { Code.Ldc_I4_8,       new KeyValuePair<int, int>(275382949, 30) },
            { Code.Ldc_I4_S,       new KeyValuePair<int, int>(275382960, 31) },
            { Code.Ldc_I4,         new KeyValuePair<int, int>(275384994, 32) },
            { Code.Ldc_I8,         new KeyValuePair<int, int>(275516067, 33) },
            { Code.Ldc_R4,         new KeyValuePair<int, int>(275647153, 34) },
            { Code.Ldc_R8,         new KeyValuePair<int, int>(275778215, 35) },
            { Code.Dup,            new KeyValuePair<int, int>(275258021, 37) },
            { Code.Pop,            new KeyValuePair<int, int>(-261875035, 38) },
            { Code.Jmp,            new KeyValuePair<int, int>(23333444, 39) },
            { Code.Call,           new KeyValuePair<int, int>(7842372, 40) },
            { Code.Calli,          new KeyValuePair<int, int>(7842377, 41) },
            { Code.Ret,            new KeyValuePair<int, int>(23440101, 42) },
            { Code.Br_S,           new KeyValuePair<int, int>(23331343, 43) },
            { Code.Brfalse_S,      new KeyValuePair<int, int>(-261868945, 44) },
            { Code.Brtrue_S,       new KeyValuePair<int, int>(-261868945, 45) },
            { Code.Beq_S,          new KeyValuePair<int, int>(-530308497, 46) },
            { Code.Bge_S,          new KeyValuePair<int, int>(-530308497, 47) },
            { Code.Bgt_S,          new KeyValuePair<int, int>(-530308497, 48) },
            { Code.Ble_S,          new KeyValuePair<int, int>(-530308497, 49) },
            { Code.Blt_S,          new KeyValuePair<int, int>(-530308497, 50) },
            { Code.Bne_Un_S,       new KeyValuePair<int, int>(-530308497, 51) },
            { Code.Bge_Un_S,       new KeyValuePair<int, int>(-530308497, 52) },
            { Code.Bgt_Un_S,       new KeyValuePair<int, int>(-530308497, 53) },
            { Code.Ble_Un_S,       new KeyValuePair<int, int>(-530308497, 54) },
            { Code.Blt_Un_S,       new KeyValuePair<int, int>(-530308497, 55) },
            { Code.Br,             new KeyValuePair<int, int>(23333376, 56) },
            { Code.Brfalse,        new KeyValuePair<int, int>(-261866912, 57) },
            { Code.Brtrue,         new KeyValuePair<int, int>(-261866912, 58) },
            { Code.Beq,            new KeyValuePair<int, int>(-530308512, 59) },
            { Code.Bge,            new KeyValuePair<int, int>(-530308512, 60) },
            { Code.Bgt,            new KeyValuePair<int, int>(-530308512, 61) },
            { Code.Ble,            new KeyValuePair<int, int>(-530308512, 62) },
            { Code.Blt,            new KeyValuePair<int, int>(-530308512, 63) },
            { Code.Bne_Un,         new KeyValuePair<int, int>(-530308512, 64) },
            { Code.Bge_Un,         new KeyValuePair<int, int>(-530308512, 65) },
            { Code.Bgt_Un,         new KeyValuePair<int, int>(-530308512, 66) },
            { Code.Ble_Un,         new KeyValuePair<int, int>(-530308512, 67) },
            { Code.Blt_Un,         new KeyValuePair<int, int>(-530308512, 68) },
            { Code.Switch,         new KeyValuePair<int, int>(-261866901, 69) },
            { Code.Ldind_I1,       new KeyValuePair<int, int>(6961829, 70) },
            { Code.Ldind_U1,       new KeyValuePair<int, int>(6961829, 71) },
            { Code.Ldind_I2,       new KeyValuePair<int, int>(6961829, 72) },
            { Code.Ldind_U2,       new KeyValuePair<int, int>(6961829, 73) },
            { Code.Ldind_I4,       new KeyValuePair<int, int>(6961829, 74) },
            { Code.Ldind_U4,       new KeyValuePair<int, int>(6961829, 75) },
            { Code.Ldind_I8,       new KeyValuePair<int, int>(7092901, 76) },
            { Code.Ldind_I,        new KeyValuePair<int, int>(6961829, 77) },
            { Code.Ldind_R4,       new KeyValuePair<int, int>(7223973, 78) },
            { Code.Ldind_R8,       new KeyValuePair<int, int>(7355045, 79) },
            { Code.Ldind_Ref,      new KeyValuePair<int, int>(7486117, 80) },
            { Code.Stind_Ref,      new KeyValuePair<int, int>(-530294107, 81) },
            { Code.Stind_I1,       new KeyValuePair<int, int>(-530294107, 82) },
            { Code.Stind_I2,       new KeyValuePair<int, int>(-530294107, 83) },
            { Code.Stind_I4,       new KeyValuePair<int, int>(-530294107, 84) },
            { Code.Stind_I8,       new KeyValuePair<int, int>(-530290011, 85) },
            { Code.Stind_R4,       new KeyValuePair<int, int>(-530281819, 86) },
            { Code.Stind_R8,       new KeyValuePair<int, int>(-530277723, 87) },
            { Code.Add,            new KeyValuePair<int, int>(-261739867, 88) },
            { Code.Sub,            new KeyValuePair<int, int>(-261739867, 89) },
            { Code.Mul,            new KeyValuePair<int, int>(-261739867, 90) },
            { Code.Div,            new KeyValuePair<int, int>(-261739867, 91) },
            { Code.Div_Un,         new KeyValuePair<int, int>(-261739867, 92) },
            { Code.Rem,            new KeyValuePair<int, int>(-261739867, 93) },
            { Code.Rem_Un,         new KeyValuePair<int, int>(-261739867, 94) },
            { Code.And,            new KeyValuePair<int, int>(-261739867, 95) },
            { Code.Or,             new KeyValuePair<int, int>(-261739867, 96) },
            { Code.Xor,            new KeyValuePair<int, int>(-261739867, 97) },
            { Code.Shl,            new KeyValuePair<int, int>(-261739867, 98) },
            { Code.Shr,            new KeyValuePair<int, int>(-261739867, 99) },
            { Code.Shr_Un,         new KeyValuePair<int, int>(-261739867, 100) },
            { Code.Neg,            new KeyValuePair<int, int>(6691493, 101) },
            { Code.Not,            new KeyValuePair<int, int>(6691493, 102) },
            { Code.Conv_I1,        new KeyValuePair<int, int>(6953637, 103) },
            { Code.Conv_I2,        new KeyValuePair<int, int>(6953637, 104) },
            { Code.Conv_I4,        new KeyValuePair<int, int>(6953637, 105) },
            { Code.Conv_I8,        new KeyValuePair<int, int>(7084709, 106) },
            { Code.Conv_R4,        new KeyValuePair<int, int>(7215781, 107) },
            { Code.Conv_R8,        new KeyValuePair<int, int>(7346853, 108) },
            { Code.Conv_U4,        new KeyValuePair<int, int>(6953637, 109) },
            { Code.Conv_U8,        new KeyValuePair<int, int>(7084709, 110) },
            { Code.Callvirt,       new KeyValuePair<int, int>(7841348, 111) },
            { Code.Cpobj,          new KeyValuePair<int, int>(-530295123, 112) },
            { Code.Ldobj,          new KeyValuePair<int, int>(6698669, 113) },
            { Code.Ldstr,          new KeyValuePair<int, int>(275908266, 114) },
            { Code.Newobj,         new KeyValuePair<int, int>(276014660, 115) },
            { Code.Castclass,      new KeyValuePair<int, int>(7513773, 116) },
            { Code.Isinst,         new KeyValuePair<int, int>(6989485, 117) },
            { Code.Conv_R_Un,      new KeyValuePair<int, int>(7346853, 118) },
            { Code.Unbox,          new KeyValuePair<int, int>(6990509, 121) },
            { Code.Throw,          new KeyValuePair<int, int>(-245061883, 122) },
            { Code.Ldfld,          new KeyValuePair<int, int>(6727329, 123) },
            { Code.Ldflda,         new KeyValuePair<int, int>(6989473, 124) },
            { Code.Stfld,          new KeyValuePair<int, int>(-530270559, 125) },
            { Code.Ldsfld,         new KeyValuePair<int, int>(275121825, 126) },
            { Code.Ldsflda,        new KeyValuePair<int, int>(275383969, 127) },
            { Code.Stsfld,         new KeyValuePair<int, int>(-261876063, 128) },
            { Code.Stobj,          new KeyValuePair<int, int>(-530298195, 129) },
            { Code.Conv_Ovf_I1_Un, new KeyValuePair<int, int>(6953637, 130) },
            { Code.Conv_Ovf_I2_Un, new KeyValuePair<int, int>(6953637, 131) },
            { Code.Conv_Ovf_I4_Un, new KeyValuePair<int, int>(6953637, 132) },
            { Code.Conv_Ovf_I8_Un, new KeyValuePair<int, int>(7084709, 133) },
            { Code.Conv_Ovf_U1_Un, new KeyValuePair<int, int>(6953637, 134) },
            { Code.Conv_Ovf_U2_Un, new KeyValuePair<int, int>(6953637, 135) },
            { Code.Conv_Ovf_U4_Un, new KeyValuePair<int, int>(6953637, 136) },
            { Code.Conv_Ovf_U8_Un, new KeyValuePair<int, int>(7084709, 137) },
            { Code.Conv_Ovf_I_Un,  new KeyValuePair<int, int>(6953637, 138) },
            { Code.Conv_Ovf_U_Un,  new KeyValuePair<int, int>(6953637, 139) },
            { Code.Box,            new KeyValuePair<int, int>(7477933, 140) },
            { Code.Newarr,         new KeyValuePair<int, int>(7485101, 141) },
            { Code.Ldlen,          new KeyValuePair<int, int>(6989477, 142) },
            { Code.Ldelema,        new KeyValuePair<int, int>(-261437779, 143) },
            { Code.Ldelem_I1,      new KeyValuePair<int, int>(-261437787, 144) },
            { Code.Ldelem_U1,      new KeyValuePair<int, int>(-261437787, 145) },
            { Code.Ldelem_I2,      new KeyValuePair<int, int>(-261437787, 146) },
            { Code.Ldelem_U2,      new KeyValuePair<int, int>(-261437787, 147) },
            { Code.Ldelem_I4,      new KeyValuePair<int, int>(-261437787, 148) },
            { Code.Ldelem_U4,      new KeyValuePair<int, int>(-261437787, 149) },
            { Code.Ldelem_I8,      new KeyValuePair<int, int>(-261306715, 150) },
            { Code.Ldelem_I,       new KeyValuePair<int, int>(-261437787, 151) },
            { Code.Ldelem_R4,      new KeyValuePair<int, int>(-261175643, 152) },
            { Code.Ldelem_R8,      new KeyValuePair<int, int>(-261044571, 153) },
            { Code.Ldelem_Ref,     new KeyValuePair<int, int>(-260913499, 154) },
            { Code.Stelem_I,       new KeyValuePair<int, int>(-798697819, 155) },
            { Code.Stelem_I1,      new KeyValuePair<int, int>(-798697819, 156) },
            { Code.Stelem_I2,      new KeyValuePair<int, int>(-798697819, 157) },
            { Code.Stelem_I4,      new KeyValuePair<int, int>(-798697819, 158) },
            { Code.Stelem_I8,      new KeyValuePair<int, int>(-798693723, 159) },
            { Code.Stelem_R4,      new KeyValuePair<int, int>(-798689627, 160) },
            { Code.Stelem_R8,      new KeyValuePair<int, int>(-798685531, 161) },
            { Code.Stelem_Ref,     new KeyValuePair<int, int>(-798681435, 162) },
            { Code.Ldelem,         new KeyValuePair<int, int>(-261699923, 163) },
            { Code.Stelem,         new KeyValuePair<int, int>(-798636371, 164) },
            { Code.Unbox_Any,      new KeyValuePair<int, int>(6727341, 165) },
            { Code.Conv_Ovf_I1,    new KeyValuePair<int, int>(6953637, 179) },
            { Code.Conv_Ovf_U1,    new KeyValuePair<int, int>(6953637, 180) },
            { Code.Conv_Ovf_I2,    new KeyValuePair<int, int>(6953637, 181) },
            { Code.Conv_Ovf_U2,    new KeyValuePair<int, int>(6953637, 182) },
            { Code.Conv_Ovf_I4,    new KeyValuePair<int, int>(6953637, 183) },
            { Code.Conv_Ovf_U4,    new KeyValuePair<int, int>(6953637, 184) },
            { Code.Conv_Ovf_I8,    new KeyValuePair<int, int>(7084709, 185) },
            { Code.Conv_Ovf_U8,    new KeyValuePair<int, int>(7084709, 186) },
            { Code.Refanyval,      new KeyValuePair<int, int>(6953645, 194) },
            { Code.Ckfinite,       new KeyValuePair<int, int>(7346853, 195) },
            { Code.Mkrefany,       new KeyValuePair<int, int>(6699693, 198) },
            { Code.Ldtoken,        new KeyValuePair<int, int>(275385004, 208) },
            { Code.Conv_U2,        new KeyValuePair<int, int>(6953637, 209) },
            { Code.Conv_U1,        new KeyValuePair<int, int>(6953637, 210) },
            { Code.Conv_I,         new KeyValuePair<int, int>(6953637, 211) },
            { Code.Conv_Ovf_I,     new KeyValuePair<int, int>(6953637, 212) },
            { Code.Conv_Ovf_U,     new KeyValuePair<int, int>(6953637, 213) },
            { Code.Add_Ovf,        new KeyValuePair<int, int>(-261739867, 214) },
            { Code.Add_Ovf_Un,     new KeyValuePair<int, int>(-261739867, 215) },
            { Code.Mul_Ovf,        new KeyValuePair<int, int>(-261739867, 216) },
            { Code.Mul_Ovf_Un,     new KeyValuePair<int, int>(-261739867, 217) },
            { Code.Sub_Ovf,        new KeyValuePair<int, int>(-261739867, 218) },
            { Code.Sub_Ovf_Un,     new KeyValuePair<int, int>(-261739867, 219) },
            { Code.Endfinally,     new KeyValuePair<int, int>(23333605, 220) },
            { Code.Leave,          new KeyValuePair<int, int>(23333376, 221) },
            { Code.Leave_S,        new KeyValuePair<int, int>(23333391, 222) },
            { Code.Stind_I,        new KeyValuePair<int, int>(-530294107, 223) },
            { Code.Conv_U,         new KeyValuePair<int, int>(6953637, 224) },
            { Code.Prefix7,        new KeyValuePair<int, int>(6554757, 248) },
            { Code.Prefix6,        new KeyValuePair<int, int>(6554757, 249) },
            { Code.Prefix5,        new KeyValuePair<int, int>(6554757, 250) },
            { Code.Prefix4,        new KeyValuePair<int, int>(6554757, 251) },
            { Code.Prefix3,        new KeyValuePair<int, int>(6554757, 252) },
            { Code.Prefix2,        new KeyValuePair<int, int>(6554757, 253) },
            { Code.Prefix1,        new KeyValuePair<int, int>(6554757, 254) },
            { Code.Prefixref,      new KeyValuePair<int, int>(6554757, 255) },
            { Code.Arglist,        new KeyValuePair<int, int>(279579301, 65024) },
            { Code.Ceq,            new KeyValuePair<int, int>(-257283419, 65025) },
            { Code.Cgt,            new KeyValuePair<int, int>(-257283419, 65026) },
            { Code.Cgt_Un,         new KeyValuePair<int, int>(-257283419, 65027) },
            { Code.Clt,            new KeyValuePair<int, int>(-257283419, 65028) },
            { Code.Clt_Un,         new KeyValuePair<int, int>(-257283419, 65029) },
            { Code.Ldftn,          new KeyValuePair<int, int>(279579300, 65030) },
            { Code.Ldvirtftn,      new KeyValuePair<int, int>(11184804, 65031) },
            { Code.Ldarg,          new KeyValuePair<int, int>(279317166, 65033) },
            { Code.Ldarga,         new KeyValuePair<int, int>(279579310, 65034) },
            { Code.Starg,          new KeyValuePair<int, int>(-257680722, 65035) },
            { Code.Ldloc,          new KeyValuePair<int, int>(279317166, 65036) },
            { Code.Ldloca,         new KeyValuePair<int, int>(279579310, 65037) },
            { Code.Stloc,          new KeyValuePair<int, int>(-257680722, 65038) },
            { Code.Localloc,       new KeyValuePair<int, int>(11156133, 65039) },
            { Code.Endfilter,      new KeyValuePair<int, int>(-240895259, 65041) },
            { Code.Unaligned,      new KeyValuePair<int, int>(10750096, 65042) },
            { Code.Volatile,       new KeyValuePair<int, int>(10750085, 65043) },
            { Code.Tailcall,       new KeyValuePair<int, int>(10750085, 65044) },
            { Code.Initobj,        new KeyValuePair<int, int>(-257673555, 65045) },
            { Code.Constrained,    new KeyValuePair<int, int>(10750093, 65046) },
            { Code.Cpblk,          new KeyValuePair<int, int>(-794527067, 65047) },
            { Code.Initblk,        new KeyValuePair<int, int>(-794527067, 65048) },
            { Code.Rethrow,        new KeyValuePair<int, int>(27526917, 65050) },
            { Code.Sizeof,         new KeyValuePair<int, int>(279579309, 65052) },
            { Code.Refanytype,     new KeyValuePair<int, int>(11147941, 65053) },
            { Code.Readonly,       new KeyValuePair<int, int>(10750085, 65054) }
        };

        Dictionary<Code, KeyValuePair<ushort, ValueTuple<int, int>>> Constants;
        List<ushort> ConstantsValues;

        public RTConstants(VMContext ctx)
        {
            Constants = new Dictionary<Code, KeyValuePair<ushort, ValueTuple<int, int>>>();
            ConstantsValues = new List<ushort>();

            //var constValues = ConstantsMap.ToList();
            //DataDescriptor.RandomGenerator.Shuffle(constValues);

            //ctx.GetRuntimeSearch.Constants_StaticCtor.Body = new CilBody();

            //foreach (var cvalue in constValues)
            //{
            //    var key = (ushort)DataDescriptor.RandomGenerator.NextInt32();
            //    for (int i = 0; i < 3; i++)
            //        if (ConstantsValues.FindIndex(f => f == key) != -1)
            //            key = (ushort)DataDescriptor.RandomGenerator.NextInt32();

            //    if (OpCodesMap.TryGetValue(cvalue.Key, out var opcodemapVal))
            //    {
            //        var pair = new KeyValuePair<ushort, ValueTuple<int, int>>((ushort)cvalue.Key, new ValueTuple<int, int>(opcodemapVal.Key, opcodemapVal.Value));

            //        Constants[cvalue.Key] = pair;
            //        ConstantsValues.Add((ushort)cvalue.Key);

            //        var constField = ctx.GetRuntimeSearch.Constants.FindField(ConstantsMap[cvalue.Key]);
            //        if (constField != null)
            //        {
            //            ctx.GetRuntimeSearch.Constants_StaticCtor.Body.Instructions.Add(new Instruction(DOpCodes.Ldnull));
            //            ctx.GetRuntimeSearch.Constants_StaticCtor.Body.Instructions.Add(new Instruction(DOpCodes.Ldc_I4, (int)Constants[cvalue.Key].Key));
            //            ctx.GetRuntimeSearch.Constants_StaticCtor.Body.Instructions.Add(new Instruction(DOpCodes.Stfld,
            //                                                                         ctx.GetRuntimeSearch.Constants.FindField(ConstantsMap[cvalue.Key])));
            //        }
            //    }
            //}

            //ctx.GetRuntimeSearch.Constants_StaticCtor.Body.Instructions.Add(new Instruction(DOpCodes.Ret));
        }

        public ushort GetKey(Code code)
        {
            return Constants[code].Key;
        }

        public ulong GetValue(Code code, ulong key)
        {
            var tuple = Constants[code].Value;

            ulong aUnsigned = (uint)tuple.Item1;
            ulong bUnsigned = (uint)tuple.Item2;

            ulong mergedValue = (aUnsigned << 32) | (bUnsigned & 0xFFFFFFFFUL);
            mergedValue ^= key; // Apply encryption

            ulong mask_xx_zz = mergedValue & 0x00FF00FF00FF00FFUL;
            ulong mask_ww_yy = mergedValue & 0xFF00FF00FF00FF00UL;
            return (mask_xx_zz << 8) | (mask_ww_yy >> 8);
        }
    }
}
